FROM jupyter/scipy-notebook

USER root

RUN mkdir /FofigySDK

COPY . /FofigySDK
WORKDIR /home/jovyan
RUN pip install /FofigySDK 
ENV GRANT_SUDO=yes
USER root
ENTRYPOINT ["tini", "-g", "--"]
CMD ["start-notebook.sh"]