FROM jupyter/scipy-notebook

USER root

RUN mkdir /FogifySDK

COPY . /FogifySDK
WORKDIR /home/jovyan
RUN pip install /FogifySDK 
ENV GRANT_SUDO=yes
USER root
ENTRYPOINT ["tini", "-g", "--"]
CMD ["start-notebook.sh"]